import Header from '@/components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import { aboutMeData, contactMeLinks, pages } from '../components/data/data'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header name={aboutMeData.name} pages={pages} />
				{children}
				<Footer contactMeLinks={contactMeLinks} />
			</body>
		</html>
	)
}
